services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=ams'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'TZ=UTC'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '6433:5432'
