
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  application:
    name: ai-managed-srs
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    model:
      embedding: bedrock-titan
      chat: bedrock-converse
    bedrock:
      converse:
        chat:
          options:
            max-tokens: 2000
            model: apac.amazon.nova-micro-v1:0
      aws:
        access-key: [hidden]
        secret-key: [hidden]
        region: ap-northeast-2
logging:
  level:
    org.springframework:
      ai.chat.client.advisor: DEBUG
      jdbc: DEBUG
