spring:
  application:
    name: ai-managed-srs
  ai:
    model:
      embedding: bedrock-titan
      chat: bedrock-converse
    bedrock:
      converse:
        chat:
          options:
            max-tokens: 2000
            model: apac.amazon.nova-micro-v1:0
      aws:
        access-key: [hidden]
        secret-key: [hidden]
        region: ap-northeast-2