server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  application:
    name: ai-managed-srs
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    model:
      embedding: bedrock-titan
      chat: bedrock-converse
    bedrock:
      converse:
        chat:
          options:
            max-tokens: 2000
            model: apac.amazon.nova-micro-v1:0
      aws:
        access-key: [hidden]
        secret-key: [hidden]
        region: ap-northeast-2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: false
logging:
  level:
    org.springframework:
      ai.chat.client.advisor: DEBUG
    org.hibernate.SQL: debug # logger에 출력하려면
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.event.internal: TRACE
